### ISSUE TITLE
GALasm is not open source

### ISSUE THREAD

**Issue by jtsiomb** [dwery/galasm#2]
You preface your introduction by saying that the reason GALasm was created is because there are no other open source GAL assemblers. At the same time right above that statement, is a prominent restriction specifying that "Commercial use is strictly forbidden". These two parts of the readme file contradict each other. Under every accepted definition of "open source" and "free software" one of the core liberties is the ability to use the software without restriction for any purpose. I can cite specific documents if you wish, but a quick look around fsf.org and opensource.org should convience you of the facts.

As it stands, unfortunately, GALasm is not open source, nor free software. Would you mind lifting that restriction, so we can finally have an open source GAL assembler? (assuming there are no others, I didn't check yet). Ideally please also select a common open source/free software license, and release your software under those terms.

**Comment by dwery** [comment]
I would be happy to, but I do not own the rights over the original source code and was unable to contact the original author.

**Comment by jtsiomb** [comment]
In that case it would be helpful to clarify that this isn't open source, somewhere in the README file. 

Actually it would be best if you could clearly identify all the parts of this project for which you do hold the copyright, and specify that these files are released under such and such open source/free software license, then explicitly specify that all these other files are goverened by the original license which is as follows.
This way people could cherry-pick all the open source parts and use them for something else, while being able to avoid the proprietary parts.
I know it takes a bit more effort, but it's really worth it to clear up any grey areas, to make this project as useful as possible to the community.
